"""Shared connector contracts and bookmaker adapter boundary."""

from .dtos import (
    ConnectorHealth,
    ConnectorHealthStatus,
    EventFeedRequest,
    EventFeedResult,
    MarketFeedRequest,
    MarketFeedResult,
    SourceCompetition,
    SourceEvent,
    SourceEventParticipant,
    SourceEventStatus,
    SourceMarket,
    SourceMarketStatus,
    SourceParticipant,
    SourcePrice,
    SourceSelection,
    SourceSport,
)
from .errors import (
    ConnectorAuthenticationError,
    ConnectorAuthorizationError,
    ConnectorCircuitOpenError,
    ConnectorConfigurationError,
    ConnectorError,
    ConnectorRateLimitedError,
    ConnectorSchemaError,
    ConnectorTimeoutError,
    ConnectorUnavailableError,
    is_retryable_connector_error,
)
from .protocol import BookmakerConnector

__all__ = [
    "BookmakerConnector",
    "ConnectorAuthenticationError",
    "ConnectorAuthorizationError",
    "ConnectorCircuitOpenError",
    "ConnectorConfigurationError",
    "ConnectorError",
    "ConnectorHealth",
    "ConnectorHealthStatus",
    "ConnectorRateLimitedError",
    "ConnectorSchemaError",
    "ConnectorTimeoutError",
    "ConnectorUnavailableError",
    "EventFeedRequest",
    "EventFeedResult",
    "MarketFeedRequest",
    "MarketFeedResult",
    "SourceCompetition",
    "SourceEvent",
    "SourceEventParticipant",
    "SourceEventStatus",
    "SourceMarket",
    "SourceMarketStatus",
    "SourceParticipant",
    "SourcePrice",
    "SourceSelection",
    "SourceSport",
    "is_retryable_connector_error",
]
